jaime:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: primero
    pid: {p: 100.0, i: 0, d: 0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: segundo
    pid: {p: 100, i: 0.0, d: 0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: tercero
    pid: {p: 100, i: 0, d: 0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: cuarto
    pid: {p: 100, i: 0, d: 0}
  
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: quinto
    pid: {p: 100, i: 0, d: 10}