# see available mappings on src/bender_joy/xbox.py

# pause button
b_pause: 'START'

# cancel goal button
b_cancel: 'B'

# high priority joystick button
b_priority: 'LB'

# movement axes
a_angular: 'LS_HORZ'
a_linear:  'LS_VERT'

# cmd velocities
max_linear_vel: 0.5   # caution: do not use values higher than 0.7 
max_angular_vel: 0.6  # caution: do not use values higher than 0.8
