controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster: 
      type: joint_state_broadcaster/JointStateBroadcaster 
    
    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    joints:
      - l3_to_l2
      - l4_to_l3
      - l5_to_l4
      - l6_to_l5
      - l7_to_l6
    publish_rate: 50

position_controller:
    ros__parameters:
      joints:
        - l3_to_l2
        - l4_to_l3
        - l5_to_l4
        - l6_to_l5
        - l7_to_l6
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort

velocity_controller:
    ros__parameters:
      joints:
        - l3_to_l2
        - l4_to_l3
        - l5_to_l4
        - l6_to_l5
        - l7_to_l6
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity
        - effort

